version: '3'

services:
  app:
    image: "sping-boo-jpa-train:lts1"
    build:
      context: .
    container_name: app
    # volumes:
    #   - .:/app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_trains
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db: 
        condition: service_healthy

  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db_trains
      POSTGRES_PASSWORD: postgres
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_trains"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8181:8080
    depends_on: 
      - db
